name = "contactpage"
compatibility_date = "2024-08-21"

main = "./.svelte-kit/cloudflare/_worker.js"

[site]
bucket = "./.svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "note8"
id = "9f0e7eeb9c1c42b985830873360070a6"
